# Generated by Django 5.2.1 on 2025-08-25 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phno', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('msg', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='postjob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=50, null=True)),
                ('company_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=30)),
                ('salary_range', models.IntegerField(default=10000)),
                ('desc', models.TextField(max_length=200)),
                ('req', models.CharField(default=1, max_length=200)),
                ('posted_by', models.TextField(max_length=20, null=True)),
                ('posted_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='In-Touch', max_length=20, null=True)),
                ('posted_by', models.TextField(max_length=20, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.postjob')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('Email', models.EmailField(default=True, max_length=254)),
                ('Role', models.CharField(default='user', max_length=20)),
                ('liurl', models.URLField(blank=True, default='NA', max_length=50, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('skills', models.CharField(max_length=200)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('otherskills', models.CharField(blank=True, max_length=200, null=True)),
                ('exp', models.SmallIntegerField(blank=True, null=True)),
                ('gclg', models.CharField(blank=True, max_length=30, null=True)),
                ('gstartingyear', models.CharField(blank=True, max_length=10, null=True)),
                ('gendingyear', models.CharField(blank=True, max_length=10, null=True)),
                ('gbranch', models.CharField(blank=True, max_length=20, null=True)),
                ('gcgpa', models.CharField(blank=True, max_length=5, null=True)),
                ('gclgadd', models.CharField(blank=True, max_length=100, null=True)),
                ('iclg', models.CharField(blank=True, max_length=30, null=True)),
                ('istartingyear', models.CharField(blank=True, max_length=10, null=True)),
                ('iendingyear', models.CharField(blank=True, max_length=10, null=True)),
                ('ibranch', models.CharField(blank=True, max_length=20, null=True)),
                ('imarks', models.CharField(blank=True, max_length=5, null=True)),
                ('schoolname', models.CharField(blank=True, max_length=30, null=True)),
                ('sscyear', models.CharField(blank=True, max_length=5, null=True)),
                ('cname', models.CharField(blank=True, max_length=50, null=True)),
                ('industry', models.CharField(blank=True, max_length=20, null=True)),
                ('cadd', models.CharField(blank=True, max_length=100, null=True)),
                ('hiringneeds', models.CharField(blank=True, max_length=50, null=True)),
                ('cemail', models.EmailField(blank=True, max_length=40, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='In-Touch', max_length=20, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.postjob')),
                ('others', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.profile')),
            ],
        ),
    ]
