# Generated by Django 5.2.6 on 2025-11-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postjob',
            name='salary_range',
            field=models.TextField(blank=True, default='$one-rupee', max_length=10, null=True),
        ),
    ]
