# Generated by Django 5.2.6 on 2025-11-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_posts_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='dislikes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
